project:
  type: website
  output-dir: docs

website:
  title: "Svatba"
  navbar:
    background: transparent
    left:
      - file: index.qmd
        text: Info
      - href: itinerary_cz.qmd
        text: ItinerÃ¡Å™
    right:
      - href: ./en
        text: ğŸ‡¬ğŸ‡§  

lang: cz
